### ISSUE TITLE
[Feature] Automatically Load CardFilter classes into CardFilterFactory

### ISSUE THREAD

**Issue by mostertb** [afrihost/trello-tools#3]
This is a feature request looking for a developer. Please comment bellow if you'd like to work on it.
---

# About
Currently when a new Card Filter is added, its class name needs to be configured in the constructor of `\AppBundle\Helper\CardFilter\CardFilterFactory` (see [CONTRIBUTING.md](/afrihost/trello-tools/blob/master/CONTRIBUTING.md) for more information). This is inconvenient and typically leads to merge conflicts when multiple people attempt to add new filters.

It would be great to replace this with some sort of *autoloading* logic that scans the `Helper/CardFilter` directory for any classes that implement `\AppBundle\Helper\CardFilter\CardFilterInterface`.

This could probably be naively done with a combination of [scan_dir()](https://www.php.net/manual/en/function.scandir.php) and [is_subclass_of()](https://www.php.net/manual/en/function.is-subclass-of.php) 

# Gotchas
You can safely assume that all the classes in the directory implement PSR-4 autoloading as this is the configuration in out `composer.json`

You'll need to update the `CONTRIBUTING.md` as part of the PR to change the update the *'Adding a New Card Filter'* section

**Comment by medlion** [comment]
Attempting this

**Comment by mostertb** [comment]
Great stuff! Go for it

**Comment by mostertb** [comment]
Implemented in #6
